# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oYYVzXz-oouNddRjTIJHa5CugoTLTiF4
"""

first_name= "avudaiappan"
last_name="vishwa"
prt= f'{first_name} [ {last_name}] is a coder'
print(prt)

a=int(input("enter the no"))
b=int(input("enter the no"))
c=int(input("enter the no"))
if a>=b  and a>=c:
  print(f"a= {a} is the greatest")
elif b>=a and b>=c:
  print(f" b= {b} is the greatest")
else:
  print(f"c= {c} is the greatest")

p="praneeth is a coder"
print(p.title())

x=3.5
p=3.4
c=3.6
print(round(p))

i=1
while i<=5:
  print("*"*i)
  i+=1

n=""
started = True
while True:
  n=input()
  if n == "start":
    if started:
      print("car is already started")
    else:
      start=False
      print("car started")
  
  elif n == "stop":
     if not started:
       print("car already stopped")
     else:
        started=False
        print('car stopped')
  elif n == "quit":
    break
  else:
    print('not applicable')

is_goodcredit= True
price=1000000
if is_goodcredit== True:
  dis=(price*10)//100
  print(dis)
else:
  dis=(price*20)//100
  print(dis)

name=input("enter the name")
if len(name)<3:
  print('must be long')
elif len(name)>50:
  print('must be smaller')
else:
  print("good")

weight=int(input("enter the weight "))
W_type=input('enter l for lbs or k for kg ')
l=
if  == 'l' or 'L':
  new_weight= weight*0.45
  print('weight in kilo is',new_weight)
if  == 'k' or 'K':
  new_weight=weight*2.2
  print('weight in pound is',new_weight)



weight=int(input("enter the weight "))
W_type=input('enter l for lbs or k for kg ')
W=W_type.lower()
print(l)
if  W== 'l' :
  new_weight= weight*0.45
  print('weight in kilo is',new_weight)
elif W== 'k':
  new_weight=weight*2.2
  print('weight in pound is',new_weight)
else:
  print("wrong")

dob= int(input("enter the year"))
age=2023-dob
print(age)